# Generated by Django 2.0.5 on 2018-05-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtimelog',
            name='scrum_entry',
        ),
        migrations.AddField(
            model_name='startendtimelog',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Time in minutes', null=True, validators=[
                django.core.validators.MaxValueValidator(1440, message="You can't log more than 24 hours in a day")]),
        ),
        migrations.AlterField(
            model_name='startendtimelog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startendtimelog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ManualTimeLog',
        ),
    ]
