# Generated by Django 2.0.5 on 2018-05-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180528_2348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartEndTimeLog',
            new_name='TimeLog',
        ),
    ]
