# Generated by Django 2.0.5 on 2018-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180527_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
